# Render Blueprint for the GPU-Yield Project (FINAL CORRECTED VERSION)

envVarGroups:
  - name: shared-vars
    envVars:
      # This is the corrected REDIS_URL definition.
      # The problematic `value: ""` line has been removed.
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: internalConnectionString # Using the more specific internal URL
      - key: SENTRY_DSN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: HCP_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"

services:
  # 1. Frontend: Next.js Web Service
  - name: next-ui
    type: web
    env: node
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: yield-api
          property: url # FIXED: 'url' is more reliable than 'host'

  # 2. Backend API: FastAPI Web Service
  - name: yield-api
    type: web
    env: python
    rootDir: api
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - fromGroup: shared-vars

  # 3. Background Worker: Redis consumer
  - name: alert-worker
    type: worker
    env: python
    rootDir: worker
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python alerts.py"
    envVars:
      - fromGroup: shared-vars

  # 4. Cron Job: Price Scraper
  - name: gpu-scraper
    type: cron
    env: python
    rootDir: scrapper
    schedule: "*/2 * * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - fromGroup: shared-vars

  # 5. Redis Instance
  - type: redis
    name: redis-cache
    plan: free